# Generated by Django 6.1.1 on 2026-10-06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_table_created_at_table_is_active_table_position_x_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='updated_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='updated_reservations',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='table',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='reservations',
                to='core.table',
            ),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['table', 'reservation_date', 'status'], name='core_reserv_table_i_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['restaurant', 'reservation_date'], name='core_reserv_rest_date_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['restaurant', 'status'], name='core_reserv_rest_stat_idx'),
        ),
        migrations.CreateModel(
            name='ReservationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(
                    choices=[
                        ('CREATED', 'Created'),
                        ('EDITED', 'Edited'),
                        ('TABLE_CHANGED', 'Table changed'),
                        ('CHECKED_IN', 'Checked in'),
                        ('NO_SHOW', 'No show'),
                        ('CANCELLED', 'Cancelled'),
                        ('COMPLETED', 'Completed'),
                        ('CORRECTED', 'Corrected'),
                    ],
                    max_length=32,
                )),
                ('previous_values', models.JSONField(blank=True, null=True)),
                ('new_values', models.JSONField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='reservation_actions',
                    to=settings.AUTH_USER_MODEL,
                )),
                ('reservation', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='history',
                    to='core.reservation',
                )),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
