# Generated by Django 6.1.1 on 2026-10-06 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_reservation_history_and_updated_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayoutObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(choices=[('CASH_COUNTER', 'Cash Counter'), ('WINDOW', 'Window')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('position_x', models.FloatField(default=0)),
                ('position_y', models.FloatField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameIndex(
            model_name='reservation',
            new_name='core_reserv_table_i_f70308_idx',
            old_name='core_reserv_table_i_idx',
        ),
        migrations.RenameIndex(
            model_name='reservation',
            new_name='core_reserv_restaur_e60f51_idx',
            old_name='core_reserv_rest_date_idx',
        ),
        migrations.RenameIndex(
            model_name='reservation',
            new_name='core_reserv_restaur_847c24_idx',
            old_name='core_reserv_rest_stat_idx',
        ),
        migrations.AddField(
            model_name='layoutobject',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layout_objects', to='core.restaurant'),
        ),
        migrations.AddField(
            model_name='layoutobject',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layout_objects', to='core.zone'),
        ),
    ]
