# Generated by Django 6.1.1 on 2026-10-09 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_customer_unique_constraints'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('points_earning_rate', models.DecimalField(decimal_places=2, default=100.0, help_text='Amount of purchase (in currency) required to earn 1 point', max_digits=10)),
                ('points_redemption_rate', models.DecimalField(decimal_places=2, default=1.0, help_text='Currency value of 1 point when redeeming', max_digits=10)),
                ('points_expiry_days', models.IntegerField(blank=True, help_text='Number of days before points expire. Null means no expiry.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_settings', to='core.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='PointTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('EARNED', 'Earned'), ('REDEEMED', 'Redeemed'), ('EXPIRED', 'Expired'), ('REVERSED', 'Reversed')], max_length=20)),
                ('points', models.IntegerField(help_text='Positive for earned, negative for redeemed/reversed')),
                ('balance_after', models.IntegerField(help_text='Customer balance after this transaction')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When these points will expire (for earned points)', null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_transactions', to='core.customer')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_transactions', to='core.order')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_transactions', to='core.payment')),
                ('related_transaction', models.ForeignKey(blank=True, help_text='Reference to original transaction if this is a reversal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversals', to='core.pointtransaction')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_transactions', to='core.restaurant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer', 'created_at'], name='core_pointt_custome_007bd5_idx'), models.Index(fields=['restaurant', 'created_at'], name='core_pointt_restaur_0766f9_idx'), models.Index(fields=['expires_at'], name='core_pointt_expires_6e72b9_idx')],
            },
        ),
    ]
