# Generated by Django 6.1.1 on 2026-10-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_loyaltysettings_pointtransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='website_enabled',
            field=models.BooleanField(default=False, help_text='Whether the restaurant website is enabled/published'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='website_url',
            field=models.URLField(blank=True, help_text='Restaurant website URL', null=True),
        ),
    ]
