# Generated by Django 6.1.1 on 2026-10-10 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_restaurant_website_enabled_restaurant_website_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_name', models.CharField(help_text='Name for the website', max_length=255)),
                ('logo', models.ImageField(blank=True, help_text='Restaurant logo', null=True, upload_to='website_requests/logos/')),
                ('colours', models.JSONField(blank=True, default=list, help_text='List of hex colour codes for website theme')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='website_requests', to='core.restaurant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebsiteRequestPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='website_requests/photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('website_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.websiterequest')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='websiterequest',
            index=models.Index(fields=['restaurant', 'status'], name='core_websit_restaur_89a92e_idx'),
        ),
        migrations.AddIndex(
            model_name='websiterequest',
            index=models.Index(fields=['status'], name='core_websit_status_59e2d2_idx'),
        ),
    ]
