# Generated by Django 6.1.1 on 2026-10-10 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_websiterequest_websiterequestphoto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiterequest',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the website requirements', null=True),
        ),
    ]
